[project]
name = "cropwiseai"
version = "0.1.0"
description = ""
authors = [
    {name = "Vijay410",email = "50883697+Vijay410@users.noreply.github.com"}
]
requires-python = ">=3.12"
dependencies = [
    "pymupdf (>=1.28.2,<2.0.0)",
    "frontend (>=0.0.3,<0.0.4)"
]

[dependency-groups]
dev = ["pytest (>=8.0)"]

[tool.poetry]
packages = [{ include = "app" }]

[tool.pytest.ini_options]
pythonpath = ["."]
testpaths = ["app/tests"]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
